name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation, Test, and Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2 # Set your AWS region here

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # Validate Terraform code
      - name: Validate Terraform Format
        run: terraform fmt -check

      - name: Validate Terraform Configuration
        run: terraform validate

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Generate a Terraform plan
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Apply Terraform configuration on approval
      - name: Apply Terraform Plan
        if: github.event_name == 'push'
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
