name: Terraform CI/CD Workflow

on:
  push:
    branches:
      - main # Trigger workflow on push to the main branch

jobs:
  validate:
    name: Validate Terraform Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2  # Set your AWS region here

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Specify your required version

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

  plan:
    name: Test Terraform Code
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS Credentials
        run: |
            echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "AWS_SECRET_ACCESS=${{ secrets.AWS_SECRET_ACCESS }}" >> $GITHUB_ENV
            echo "AWS_DEFAULT_REGION=eu-west-2" >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Save Plan for Later Steps
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: plan

    steps:
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        run: terraform init

      - name: Manual Approval
        uses: flycise/approve-action@v1 # Action for manual approval

      - name: Apply Terraform Plan
        run: terraform apply tfplan
